<header>
	<h2>КУПИТЬ</h2>
	<section class="brown">
		<nav>
			<ul>
				<li><a href="<?php echo $this->url(array(), 'shop-items'); ?>">Готовые работы</a></li>
				<li><a href="<?php echo $this->url(array(), 'shop-materials'); ?>">Материалы и аксессуары</a></li>
				<li>Оформление заявки</li>
			</ul>
		</nav>
	</section>
</header>
            
<section id="items">
	<article><br><br>
		<header><h3><?php echo implode($this->messages); ?></h3></header>
	</article>
</section>