<h1>Удаление фотографии с описанием из мастер-класса</h1>
    <section id="content_wrapper">
        <p>Вы уверены, что хотите удалить фото и описание к ней из мастер-класса?</p><br>
        		
        <img class="master" src="/mclasses/<?php echo $this->escape($this->block['mc_id']); ?>/<?php echo $this->escape($this->block['img']); ?>">
        <form action="<?php echo $this->url(array('id' => $this->escape($this->block['img_id'])), 'admin-mclasses-delblock'); ?>" method="post">
        	<button class="green" type="submit" name="id" value="<?php echo $this->escape($this->block['img_id']); ?>">УДАЛИТЬ</button>
        	<a class="gray btn" href="<?php echo $this->url(array('id' => $this->escape($this->block['mc_id'])), 'admin-mclasses-display', true); ?>">ОТМЕНА</a>
        </form>
    </section>