<h1>Удаление виртуального мастер-класса</h1>
    <section id="content_wrapper">
        <p>Вы уверены, что хотите удалить мастер-класс 
        		<span class="bold">"<?php echo $this->escape($this->mclass['title']); ?>"</span> из базы данных?</p>
        <form action="<?php echo $this->url(array('id' => $this->escape($this->mclass['mc_id'])), 'admin-mclasses-delete'); ?>" method="post">
        	<button class="green" type="submit" name="id" value="<?php echo $this->escape($this->mclass['mc_id']); ?>">УДАЛИТЬ</button>
        	<a class="gray btn" href="<?php echo $this->url(array(), 'admin-mclasses-index'); ?>">ОТМЕНА</a>
        </form>
    </section>