<h1>Виртуальные мастер-классы мастерской "Рыжая Соня"</h1>
<?php if($this->messages):?><div id="user_msg" class="success"><?php echo implode($this->messages); ?></div><?php endif;?>
    <section id="content_wrapper">
	    <?php if (count($this->mclasses)): ?>
				<table id="prod_tbl">
		        	<thead>
		            	<tr>
		                	<td>Фото</td>
		                	<td>Название мк</td>
		                    <td>Краткое описание</td>
		                    <td>Добавлен</td>
		                    <td class="actions_icons">Действия</td>
		                </tr>
		            </thead>
		            <tbody>
						<?php foreach ($this->mclasses as $mc): ?>
							<tr>
			                    <td><img class="master" src="/mclasses/<?php echo $this->escape($mc['mc_id']); ?>/<?php echo $this->escape($mc['img']); ?>"></td>
			                    <td><?php echo $this->escape($mc['title']); ?></td>
			                    <td class="left_txt"><?php echo $this->escape($mc['desc']); ?></td>
			                    <td><?php echo date('d.m.Y', $this->escape($mc['created'])); ?></td>

			                    <td>
			                    	<a href="<?php echo $this->url(array('id' => $this->escape($mc['mc_id'])), 'admin-mclasses-display', true); ?>">
			                    		<img src="/images/eye.png" title='Просмотр'></a>
			                        <a href="<?php echo $this->url(array('id' => $this->escape($mc['mc_id'])), 'admin-mclasses-delete', true); ?>">
			                        	<img src="/images/cancel(3).png" title="Удалить"></a>
			                    </td>
			                </tr>
						<?php endforeach; ?>
					</tbody>
		        </table>
	        	<aside class="pagination">Страницы <?php echo $this->pages; ?></aside>
        	
		<?php else: ?>
			<p>Пока нет ни одного мастеркласса</p>
		<?php endif; ?>
		<a class="green btn" href="<?php echo $this->url(array(), 'admin-mclasses-create'); ?>">ДОБАВИТЬ МАСТЕР-КЛАСС</a>
	</section>