<h1>Удаление записи из расписания мастер-классов</h1>
    <section id="content_wrapper">
        <p>Вы уверены, что хотите удалить запись 
        		<span class="bold">"<?php echo $this->escape($this->mc['title']); ?>"</span> из базы данных?</p>
        <form action="<?php echo $this->url(array('id' => $this->escape($this->mc['mc_id'])), 'admin-schedule-delete'); ?>" method="post">
        	<button class="green" type="submit" name="id" value="<?php echo $this->escape($this->mc['mc_id']); ?>">УДАЛИТЬ</button>
        	<a class="gray btn" href="<?php echo $this->url(array(), 'admin-schedule-index'); ?>">ОТМЕНА</a>
        </form>
    </section>