<h1>Расписание Мастер-классов</h1>
<?php if($this->messages):?><div id="user_msg" class="success"><?php echo implode($this->messages); ?></div><?php endif;?>
    <section id="content_wrapper">
	    <?php if (count($this->mclasses)): ?>
				<table id="prod_tbl">
		        	<thead>
		            	<tr>
		                	<td>Дата проведения</td>
		                    <td>Название</td>
		                    <td>Описание мк</td>
		                    <td>Место проведения</td>
		                    <td>Добавлен</td>
		                    <td class="action_icons">Действия</td>
		                </tr>
		            </thead>
		            <tbody>
						<?php foreach ($this->mclasses as $mc): ?>
							<tr>
			                    <td><?php echo date('d.m.Y', $this->escape($mc['date'])); ?></td>
			                    <td><?php echo $this->escape($mc['title']); ?></td>
			                    <td class="left_txt"><?php echo nl2br(mb_strcut($this->escape($mc['description']), 0, 1000)); ?>... </td>
			                    <td><?php echo $this->escape($mc['place']); ?></td>
			                    <td><?php echo date('d.m.Y', $this->escape($mc['created'])); ?></td>
			                    <td>
			                    	<a href="<?php echo $this->url(array('id' => $this->escape($mc['mc_id'])), 'admin-schedule-update', true); ?>">
			                    		<img src="/images/edit1.png" title="Редактировать"></a>
			                        <a href="<?php echo $this->url(array('id' => $this->escape($mc['mc_id'])), 'admin-schedule-delete', true); ?>">
			                        	<img src="/images/cancel(3).png" title="Удалить"></a>
			                    </td>
			                </tr>
						<?php endforeach; ?>
					</tbody>
		        </table>
	        	<aside class="pagination">Страницы <?php echo $this->pages; ?></aside>
        	
		<?php else: ?>
			<p>Пока нет ни одной записи в расписании</p>
		<?php endif; ?>
		<a class="green btn" href="<?php echo $this->url(array(), 'admin-schedule-create'); ?>">ДОБАВИТЬ МК</a>
	</section>