<h1>Удаление записи из раздела "Полезные ссылки"</h1>
    <section id="content_wrapper">
        <p>Вы уверены, что хотите удалить ссылку 
        		<span class="bold">"<?php echo $this->escape($this->link['title']); ?>"</span> из базы данных?</p>
        <form action="<?php echo $this->url(array('id' => $this->escape($this->link['link_id'])), 'admin-links-delete'); ?>" method="post">
        	<button class="green" type="submit" name="id" value="<?php echo $this->escape($this->link['link_id']); ?>">УДАЛИТЬ</button>
        	<a class="gray btn" href="<?php echo $this->url(array(), 'admin-links-index'); ?>">ОТМЕНА</a>
        </form>
    </section>