<h1>Удаление текстового блока с раздела "Познакомимся"</h1>
    <section id="content_wrapper">
        <p>Вы уверены, что хотите удалить блок 
        		<span class="bold">"<?php echo $this->escape($this->post['title']); ?>"</span> из базы данных?</p>
        <form action="<?php echo $this->url(array('id' => $this->escape($this->post['post_id'])), 'admin-events-delete'); ?>" method="post">
        	<button class="green" type="submit" name="id" value="<?php echo $this->escape($this->post['post_id']); ?>">УДАЛИТЬ</button>
        	<a class="gray btn" href="<?php echo $this->url(array(), 'admin-events-index'); ?>">ОТМЕНА</a>
        </form>
    </section>