<h1>Мастера</h1>
<?php if($this->messages):?><div id="user_msg" class="success"><?php echo implode($this->messages); ?></div><?php endif;?>
    <section id="content_wrapper">
	    <?php if (count($this->posts)): ?>
			<table id="prod_tbl">
	        	<thead>
	            	<tr>
	                	<td>Фото</td>
	                    <td>Заголовок</td>
	                    <td>Текст блока</td>
	                    <td class="action_icons">Действия</td>
	                </tr>
	            </thead>
	            <tbody>
					<?php foreach ($this->posts as $post): ?>
						<tr>
		                    <td><img class="master" src="/foto/<?php echo $this->escape($post['img']); ?>"></td>
		                    <td><?php echo $this->escape($post['title']); ?></td>
		                    <td class="left_txt"><?php echo nl2br($this->escape($post['post'])); ?></td>
		                    <td>
		                    	<a href="<?php echo $this->url(array('id' => $this->escape($post['post_id'])), 'admin-events-update', true); ?>">
		                    		<img src="/images/edit1.png" title="Редактировать"></a>
		                        <a href="<?php echo $this->url(array('id' => $this->escape($post['post_id'])), 'admin-events-delete', true); ?>">
		                        	<img src="/images/cancel(3).png" title="Удалить"></a>
		                    </td>
		                </tr>
					<?php endforeach; ?>
				</tbody>
	        </table>
        
        
		<?php else: ?>
			<p>Пока нет ни одной записи в разделе "Познакомимся"</p>
		<?php endif; ?>
		<a class="green btn" href="<?php echo $this->url(array(), 'admin-events-create'); ?>">ДОБАВИТЬ БЛОК</a>
	</section>