<header>
	<h2>ОБО ВСЕМ<span class="top_header"> &mdash; Блог</span></h2>
	<section class="brown">
		<nav>
			<ul>
				<li><a href="<?php echo $this->url(array(), 'blog'); ?>">Блог</a></li>
                <li><a href="<?php echo $this->url(array(), 'questions'); ?>">Ответы на вопросы</a></li>
			</ul>
		</nav>
	</section>
</header>
            

<section class="post_view">
	<article>
		<header><h2><?php echo $this->escape($this->post['title']); ?></h2></header>
		<?php foreach ($this->blocks as $block): ?>
			<img class="imgframe" src="/blogfotos/<?php echo $this->escape($block['post_id']); ?>/<?php echo $this->escape($block['img']); ?>">
			<p><?php echo nl2br($this->escape($block['description'])); ?></p>
		<?php endforeach; ?>
		<aside class="postdate"><?php echo date('d.m.Y', $this->escape($this->post['created'])); ?></aside>
	</article>
</section>

<h3>Добавить комментарий</h3>
<section id="comment_form">
	<?php echo $this->form; ?>
</section>



<h3>Комментарии :</h3>
<?php if (count($this->comments)): ?>
	<section id="comments">
		<?php foreach ($this->comments as $comment): ?>
			<article class="btmline">
				<header><h3><?php echo $this->escape($comment['name']); ?></h3><?php echo date('d.m.Y', $this->escape($comment['created'])); ?></header>
				<p><?php echo  nl2br($this->escape($comment['comment'])); ?></p>
			</article>
		<?php endforeach; ?>
	</section>
<?php else: ?>
	<section id="comments">
		<p>Комментариев пока нет</p>
	</section>
<?php endif; ?>
