<h1>Сообщения пользователей со страницы "Контакты"</h1>
<?php if($this->messages):?><div id="user_msg" class="success"><?php echo implode($this->messages); ?></div><?php endif;?>
    <section id="content_wrapper">
	    <?php if (count($this->inbox)): ?>
				<table id="prod_tbl">
		        	<thead>
		            	<tr>
		                	<td>Имя пользователя</td>
		                    <td>Текст сообщения</td>
		                    <td>E-mail</td>
		                    <td>Принято</td>
		                    <td class="action_icons">Действия</td>
		                </tr>
		            </thead>
		            <tbody>
						<?php foreach ($this->inbox as $msg): ?>
							<tr>
			                    <td><?php echo $this->escape($msg['name']); ?></td>
			                    <td class="left_txt"><?php echo nl2br($this->escape($msg['text'])); ?></td>
			                    <td><?php echo $this->escape($msg['email']); ?></td>
			                    <td><?php echo date('d.m.Y', $this->escape($msg['created'])); ?></td>
			                    <td>
			                    	<a href="<?php echo $this->url(array('id' => $this->escape($msg['message_id'])), 'admin-messages-answer', true); ?>">
			                    		<img src="/images/replay.png" title="Ответить на E-mail"></a>
			                        <a href="<?php echo $this->url(array('id' => $this->escape($msg['message_id'])), 'admin-messages-delete', true); ?>">
			                        	<img src="/images/cancel(3).png" title="Удалить"></a>
			                    </td>
			                </tr>
						<?php endforeach; ?>
					</tbody>
		        </table>
	        	<aside class="pagination">Страницы <?php echo $this->pages; ?></aside>
        	
		<?php else: ?>
			<p>Сообщений нет</p>
		<?php endif; ?>
	</section>