<h1>Удаление информации о сотруднике</h1>
    <section id="content_wrapper">
        <p>Вы уверены, что хотите удалить информацию о сотруднике 
        		<span class="bold"><?php echo $this->escape($this->master['name']); ?></span> из базы данных?</p>
        <form action="<?php echo $this->url(array('id' => $this->escape($this->master['master_id'])), 'admin-masters-delete'); ?>" method="post">
			
        	<button class="green" type="submit" name="id" value="<?php echo $this->escape($this->master['master_id']); ?>">УДАЛИТЬ</button>
        	<a class="gray btn" href="<?php echo $this->url(array(), 'admin-masters-index'); ?>">ОТМЕНА</a>
        </form>
    </section>