<h1>Удаление фотографии товара</h1>
    <section id="content_wrapper">
        <img class="pictures_of_item" src="/foto/<?php echo $this->escape($this->pic['img']); ?>">
        <p>Вы уверены, что хотите удалить выбранное фото товара?</p>
        <form action="<?php echo $this->url(array('id' => $this->escape($this->pic['img_id'])), 'admin-items-images-delete'); ?>" method="post">
        	<button class="green" type="submit" name="id" value="<?php echo $this->escape($this->pic['img_id']); ?>">УДАЛИТЬ</button>
        	<a class="gray btn" href="<?php echo $this->url(array('id' => $this->escape($this->pic['item_id'])), 'admin-items-images'); ?>">ОТМЕНА</a>
        </form>
    </section>