<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Панель администратора &laquo;РЫЖАЯ СОНЯ&raquo;</title>
<!--[if IE]>
	<script>
		document.createElement('header');
		document.createElement('nav');
		document.createElement('section');
		document.createElement('article');
		document.createElement('aside');
		document.createElement('footer');
	</script>
	<![endif]-->
<link rel="stylesheet" href="/css/admin.css" type="text/css">
</head>

<body>

<header id="page_header">
	<img class="logo" src="/images/logo-small.png">
</header>

<section id="content">
	<?php echo $this->layout()->content; ?>
</section>

<footer id="page_footer">
	&copy; &laquo;Рыжая Соня&raquo; 2013 г.
</footer>

</body>
</html>